import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import CustomNavbar from "./components/Navbar/Navbar";
import "bootstrap-icons/font/bootstrap-icons.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{
  paddingTop: '80px' }}>
        <StoreProvider>
          <CustomNavbar />
          
          <div className="flex-1">
            <main className="container mx-auto py-4 mt-16">
              {children}
            </main>
          </div>
          
          <footer className="bg-dark text-white py-3 w-full">
            <div className="container mx-auto text-center">
              <small>© Todos los derechos reservados</small>
            </div>
          </footer>
        </StoreProvider>
      </body>
    </html>
  );
}